# Site settings
title: Dean Markwick 
email: <dean.markwick@talk21.com> 
description: # > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
#url: "http:/localhost:4000" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  dm13450
linkedin_url: deanmarkwick13450 

# Build settings
markdown: kramdown
